swagger: "2.0"
info:
  description: "It allows you to create a model for CARISA software. CARISA is a platform for the development of real-time information environments. Very suitable for IOT systems. With this API you will be able to control the whole CARISA platform."
  version: "1.0.0"
  title: "CARISA API"
  contact:
    email: "dav.sua.pas@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/api"
tags:
  - name: "instance"
    description: "Instance represents a set of spaces independently of another instance in all system"
  - name: "space"
    description: "The space splits the instance in logic categories"
schemes:
  - "https"
  - "http"
paths:
  /instances:
    post:
      tags:
        - "instance"
      summary: "Add a new instance to the platform"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Instance object that needs to be added to the platform"
          required: true
          schema:
            $ref: "#/definitions/InstanceReq"
      responses:
        "201":
          description: "Instance created"
          schema:
            $ref: "#/definitions/Instance"
        "302":
          description: "Instance found"
        "400":
          description: "Invalid input"
        "500":
          description: "Internal server error"
  /instances/{id}:
    put:
      tags:
        - "instance"
      summary: "If the instance ID exists is updated otherwise is added"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "Instance identifier"
          type: string
          required: true
        - in: "body"
          name: "body"
          description: "Instance object that needs to be added or updated to the platform"
          required: true
          schema:
            $ref: "#/definitions/InstanceReq"
      responses:
        "200":
          description: "Instance updated"
          schema:
            $ref: "#/definitions/Instance"
        "201":
          description: "Instance created"
          schema:
            $ref: "#/definitions/Instance"
        "400":
          description: "Invalid input"
        "500":
          description: "Internal server error"
    get:
      tags:
        - "instance"
      summary: "Find instance by ID"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "Instance identifier"
          type: string
          required: true
      responses:
        "200":
          description: "Instance found"
          schema:
            $ref: "#/definitions/Instance"
        "400":
          description: "Invalid input"
        "404":
          description: "Instance not found"
        "500":
          description: "Internal server error"
  /instances/{id}/spaces:
    get:
      tags:
        - "instance"
      summary: "List spaces of the instance by ID"
      description: "The 'sname' and 'gtname' query parameters are exclusive. The 'top' query parameter must be between 1 and 100."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "Instance identifier"
          type: string
          required: true
        - in: "query"
          name: "sname"
          description: "List spaces that start by 'sname'"
          type: string
        - in: "query"
          name: "gtname"
          description: "List spaces greater or equal than 'sname'"
          type: string
        - in: "query"
          name: "top"
          description: "Limit of spaces"
          type: integer
          minimum: 1
          maximum: 100
      responses:
        "200":
          description: "Successful request"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SpaceLink"
        "400":
          description: "Invalid input"
        "500":
          description: "Internal server error"
  /spaces:
    post:
      tags:
        - "space"
      summary: "Add a new space to the instance"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Space object that needs to be added to the instance"
          required: true
          schema:
            $ref: "#/definitions/SpaceReq"
      responses:
        "201":
          description: "Space created"
          schema:
            $ref: "#/definitions/Space"
        "302":
          description: "Space found"
        "400":
          description: "Invalid input"
        "404":
          description: "Instance not found"
        "500":
          description: "Internal server error"
  /spaces/{id}:
    put:
      tags:
        - "space"
      summary: "If the space ID exists is updated otherwise is added."
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "Space identifier"
          type: string
          required: true
        - in: "body"
          name: "body"
          description: "Space object that needs to be added or updated to the platform"
          required: true
          schema:
            $ref: "#/definitions/SpaceReq"
      responses:
        "200":
          description: "Space updated"
          schema:
            $ref: "#/definitions/Space"
        "201":
          description: "Space created"
          schema:
            $ref: "#/definitions/Space"
        "400":
          description: "Invalid input"
        "500":
          description: "Internal server error"
    get:
      tags:
        - "space"
      summary: "Find space by ID"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "id"
          description: "Space identifier"
          type: string
          required: true
      responses:
        "200":
          description: "Space found"
          schema:
            $ref: "#/definitions/Space"
        "400":
          description: "Invalid input"
        "404":
          description: "Space not found"
        "500":
          description: "Internal server error"
definitions:
  Instance:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Instance identifier"
      name:
        type: "string"
        description: "Instance name"
      description:
        type: "string"
        description: "Instance description"
  InstanceReq:
    type: "object"
    required:
      - "name"
      - "description"
    properties:
      name:
        type: "string"
        maxLength: 50
        description: "Instance name"
      description:
        type: "string"
        maxLength: 500
        description: "Instance description"
  Space:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Space identifier"
      name:
        type: "string"
        description: "Space name"
      description:
        type: "string"
        description: "Space description"
      instanceId:
        type: "string"
        description: "Instance identifier where the space has been added"
  SpaceReq:
    type: "object"
    required:
      - "name"
      - "description"
    properties:
      name:
        type: "string"
        maxLength: 50
        description: "Space name"
      description:
        type: "string"
        maxLength: 500
        description: "Space description"
      instanceId:
        type: "string"
        description: "Instance identifier where the space is added"
  SpaceLink:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Space name"
      spaceId:
        type: "string"
        description: "Space identifier"
